name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version

    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        NEW_VERSION: ${{steps.version.outputs.version}}
      run: |
        docker login -u $ -p $DOCKER_PASSWORD
        echo "New version: $NEW_VERSION!!!
    
    
#     - name: Build docker image
#       run: |
#         docker build -t andywarrior07/docker-graphql:0.0.2 .
#         docker build -t andywarrior07/docker-graphql:latest .
      
#     - name: Push docker image
#       run: |
#         docker push andywarrior07/docker-graphql:0.0.2
#         docker push andywarrior07/docker-graphql:latest

    
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
